services:
  - type: web
    name: gesture-control
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
